### ISSUE TITLE
identificador de municipios

### ISSUE THREAD

**Issue by medfdez** [yudivian/cuba-geojsons#2]
Seria posible que le adicionara un identificador a cada municipio para poder tener referencia

**Comment by elpbatista** [comment]
Pienso que hay que mirar las fuentes de donse salió la cartografía orginal porque esos identificadores ya existen. Creo recordar que el antiguo catastro tenía algo como núcleos problacionales, sería bueno incluir esa información proveniente de fuentes autorizadas y darles la atribución en algún lugar, tal vez en el README.md

**Comment by yudivian** [comment]
Los identificadores originales eran un desastre. Solo opté inicialmente poner identificadores provinciales porque esos están más extendidos, la idea es entre todos ir buscando los mejores identificadores y poner su atribución. Hoy, en un rato pondré las fuentes originales desde donde construí los datos, para dar el crédito y además que se puedan consultar. Prioricé en primera instancia la publicación, de hecho fueron usados en Postdata aún con problemas y hasta que no estuvieron un poco más decente, no los publicamos. Ahora, entre todos, mejorarlos lo más que podamos. Gracias.

**Comment by yudivian** [comment]
Ya añadí los códigos oficiales tanto de provincias como de municipios. Los códigos salieron de la Resolución 129/2010 de la ONEI (en ese entonces ONE) que establece de manera actualizada  el “Codificador de la División Político-Administrativa” . Utilicé este porque de esta manera se alínean los codificadores de los datos geográficos con aquellos usados en las estadísticas oficiales. Los códigos aparecen como DPA_province_code , para las provincias, y DPA_municipality_code, para los municipios. Cualquier otra cosa lo comentan. Saludos.

**Comment by yudivian** [comment]
Done!
